"""
validate.py — purple-team validation harness.

    python validate.py

Fixes "not tested against attacks": every MITRE technique in the
detection catalog gets its attack emulated through a FRESH engine, with
an explicit expectation. Benign traffic is validated too — a pipeline
that alerts on normal behavior fails validation just as hard as one
that misses an attack.

Writes docs/VALIDATION.md and exits non-zero on any failure, so CI
blocks merges that break a detection (detection regression testing).
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from itdr.engine import ITDREngine
from itdr.simulator import (scenario_benign, scenario_impossible_travel,
                            scenario_mfa_fatigue, scenario_token_theft)
from itdr.detections import DEFAULT_ENRICHER

CASES = [
    {
        "technique": "T1110-negative",
        "name": "Benign workday (must stay silent)",
        "scenario": scenario_benign,
        "expect_alert": False,
        "expect_checkers": set(),
    },
    {
        "technique": "T1621",
        "name": "MFA fatigue / push bombing",
        "scenario": scenario_mfa_fatigue,
        "expect_alert": True,
        "expect_checkers": {"mfa_fatigue"},
    },
    {
        "technique": "T1550.004",
        "name": "Session token theft (AiTM replay + TOR + refresh)",
        "scenario": scenario_token_theft,
        "expect_alert": True,
        "expect_checkers": {"session_mutation", "tor_access",
                            "refresh_replay"},
        "expect_tier": "CRITICAL",
    },
    {
        "technique": "T1078",
        "name": "Impossible travel",
        "scenario": scenario_impossible_travel,
        "expect_alert": True,
        "expect_checkers": {"impossible_travel"},
    },
]


def run_case(case: dict) -> dict:
    engine = ITDREngine()
    alerts = []
    for _, ev in case["scenario"]():
        alerts.extend(engine.process_event(ev))

    fired = {d.checker for a in alerts for d in a.detections}
    tiers = {a.tier for a in alerts}

    ok = (bool(alerts) == case["expect_alert"]
          and case["expect_checkers"] <= fired
          if case["expect_alert"] else not alerts)
    if ok and case.get("expect_tier"):
        ok = case["expect_tier"] in tiers

    return {
        "technique": case["technique"], "name": case["name"],
        "expected": ("alert: " + "+".join(sorted(case["expect_checkers"]))
                     if case["expect_alert"] else "silence"),
        "observed": ("+".join(sorted(fired)) + f" [{','.join(sorted(tiers))}]"
                     if alerts else "silence"),
        "passed": ok,
    }


def main() -> None:
    results = [run_case(c) for c in CASES]

    rows = ["| Technique | Emulated attack | Expected | Observed | Result |",
            "|---|---|---|---|---|"]
    for r in results:
        mark = "✅ PASS" if r["passed"] else "❌ FAIL"
        rows.append(f"| {r['technique']} | {r['name']} | {r['expected']} "
                    f"| {r['observed']} | {mark} |")

    doc = "\n".join([
        "# Detection Validation Report",
        "",
        f"> Auto-generated by `validate.py` on "
        f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}. "
        "Every detection is validated against an emulation of the attack "
        "it claims to catch — and benign traffic is validated for "
        "silence. CI fails if any row fails.",
        "",
        "\n".join(rows),
        "",
    ])
    out = Path(__file__).parent / "docs" / "VALIDATION.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(doc)

    for r in results:
        status = "PASS" if r["passed"] else "FAIL"
        print(f"[{status}] {r['technique']:<16} {r['name']}")
    failed = [r for r in results if not r["passed"]]
    print(f"\n{len(results) - len(failed)}/{len(results)} validations "
          f"passed -> {out}")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
